#### **Nonlinear Optimisation Workshop Lab Sheet 2**
###### **Eishita Kalra 2746904**

In [1]:
from pi_approx import pi_iter1_arctan as pi1
from pi_approx import pi_iter2_archim as pi2
from pi_approx import pi_iter3_borwein as pi3

import numpy as np


In [2]:
seq1 = np.array(pi1(11))
(seq1[1:11]-np.pi)/(seq1[0:10]-np.pi)
#no evidence its bounded
#sublinear

array([-0.55326412, -0.684473  , -0.75784144, -0.80408452, -0.83571393,
       -0.85864606, -0.87600766, -0.88959635, -0.9005153 , -0.90947765])

In [3]:
seq2 = np.array(pi2(11))
(seq2[1:11]-np.pi)/(seq2[0:10]-np.pi)
#linear convergence seen very clearly

array([0.22882358, 0.24482198, 0.24871256, 0.24967858, 0.24991967,
       0.24997992, 0.24999498, 0.24999875, 0.24999969, 0.24999992])

In [4]:
seq3 = np.array(pi3(11))
(seq3[1:11]-np.pi)/(seq3[0:10]-np.pi)
#dividing by 0
#by 4 iterate got to the exact value of pi

/tmp/ipykernel_11407/1854849518.py:2: RuntimeWarning: invalid value encountered in divide
  (seq3[1:11]-np.pi)/(seq3[0:10]-np.pi)


array([3.71981869e-03, 7.27369002e-06, 0.00000000e+00,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan])

2. (d) Try Armijo and Wolfe line searches. Count function evaluations.

Go back to the steepest descent direction (direction = ’SD’ and change the line search to the back- trackingArmijolinesearch(linesearch = ’Armijo’–bothchangesinGenericLineSearchMethod.py). Use a parameter of c1 = 0.1 (this should be the default).

 Again, run LineSearchPlot.py an observe the pattern. 
 
 Also inspect the number of iterations and function evaluations necessary to find the local minimum. 
27 iterations
LS 3
GLSM 99
 
 You should find that the number of iterations does not change much while the number of function evaluations reduces drastically. 
 
 Play around with different values for the c1 parameter (c1 = 0.9 gives an interesting plot. Please try to explain what happens here!). 
60 iterations
LS 3
GLSM 288

goes off track less
goes straight to point
took too many iterations smooth curve
